import type { ImageSource } from 'expo-image';

const exerciseImages: Record<string, ImageSource> = {
  'leg-press': require('../../assets/exercises/leg-press.png'),
  'bench-press': require('../../assets/exercises/bench-press.png'),
  'lat-pulldown': require('../../assets/exercises/lat-pulldown.png'),
  'lateral-raise': require('../../assets/exercises/lateral-raise.png'),
  'cable-crunch': require('../../assets/exercises/cable-crunch.png'),
  'romanian-deadlift': require('../../assets/exercises/romanian-deadlift.png'),
  'incline-dumbbell-press': require('../../assets/exercises/incline-dumbbell-press.png'),
  'seated-cable-row': require('../../assets/exercises/seated-cable-row.png'),
  'dumbbell-biceps-curl': require('../../assets/exercises/dumbbell-biceps-curl.png'),
  'goblet-squat': require('../../assets/exercises/goblet-squat.png'),
  'machine-shoulder-press': require('../../assets/exercises/machine-shoulder-press.png'),
  'face-pull': require('../../assets/exercises/face-pull.png'),
  'cable-triceps-pushdown': require('../../assets/exercises/cable-triceps-pushdown.png'),
  'hack-squat': require('../../assets/exercises/hack-squat.png'),
  'barbell-hip-thrust': require('../../assets/exercises/barbell-hip-thrust.png'),
  'bulgarian-split-squat': require('../../assets/exercises/bulgarian-split-squat.png'),
  'lying-leg-curl': require('../../assets/exercises/lying-leg-curl.png'),
  'assisted-pull-up': require('../../assets/exercises/assisted-pull-up.png'),
  'chest-supported-dumbbell-row': require('../../assets/exercises/chest-supported-dumbbell-row.png'),
  'pec-deck-fly': require('../../assets/exercises/pec-deck-fly.png'),
  'standing-calf-raise': require('../../assets/exercises/standing-calf-raise.png'),
  'pallof-press': require('../../assets/exercises/pallof-press.png'),
  'barbell-back-squat': require('../../assets/exercises/barbell-back-squat.png'),
  'leg-extension': require('../../assets/exercises/leg-extension.png'),
  'hammer-curl': require('../../assets/exercises/hammer-curl.png'),
  'overhead-triceps-extension': require('../../assets/exercises/overhead-triceps-extension.png'),
  plank: require('../../assets/exercises/plank.png'),
  'side-plank': require('../../assets/exercises/side-plank.png'),
  'hanging-knee-raise': require('../../assets/exercises/hanging-knee-raise.png'),
  'dead-bug': require('../../assets/exercises/dead-bug.png'),
  'dumbbell-bench-press': require('../../assets/exercises/dumbbell-bench-press.png'),
  'push-up': require('../../assets/exercises/push-up.png'),
  'dumbbell-shoulder-press': require('../../assets/exercises/dumbbell-shoulder-press.png'),
  'pull-up': require('../../assets/exercises/pull-up.png'),
  'barbell-bent-over-row': require('../../assets/exercises/barbell-bent-over-row.png'),
  'one-arm-dumbbell-row': require('../../assets/exercises/one-arm-dumbbell-row.png'),
  'barbell-deadlift': require('../../assets/exercises/barbell-deadlift.png'),
  'walking-lunge': require('../../assets/exercises/walking-lunge.png'),
  'seated-leg-curl': require('../../assets/exercises/seated-leg-curl.png'),
  'seated-calf-raise': require('../../assets/exercises/seated-calf-raise.png'),
  'reverse-pec-deck': require('../../assets/exercises/reverse-pec-deck.png'),
  'preacher-curl': require('../../assets/exercises/preacher-curl.png'),
  'lying-triceps-extension': require('../../assets/exercises/lying-triceps-extension.png'),
  'ab-wheel-rollout': require('../../assets/exercises/ab-wheel-rollout.png'),
  'reverse-crunch': require('../../assets/exercises/reverse-crunch.png'),
};

export function exerciseArtFor(exerciseId: string) {
  return exerciseImages[exerciseId] ?? exerciseImages['leg-press'];
}
