import type { Exercise } from './types';

export const exercises: Exercise[] = [
  { id: 'leg-press', name: 'Leg Press', muscleGroups: ['Quads', 'Glutes'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your lower back supported and drive through your whole foot.' },
  { id: 'bench-press', name: 'Bench Press', muscleGroups: ['Chest', 'Triceps'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Pin your shoulder blades, lower with control, and press over your chest.' },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroups: ['Back', 'Biceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Pull your elbows toward your ribs without leaning far back.' },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroups: ['Shoulders'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '12–15 reps', instructions: 'Lead with your elbows and stop near shoulder height.' },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroups: ['Core'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Curl your ribs toward your pelvis without pulling with your arms.' },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroups: ['Hamstrings', 'Glutes'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Push your hips back and keep the bar close to your legs.' },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', muscleGroups: ['Chest', 'Shoulders'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Set a low incline and press the dumbbells slightly inward.' },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroups: ['Back', 'Biceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your torso tall and bring the handle toward your lower ribs.' },
  { id: 'dumbbell-biceps-curl', name: 'Dumbbell Biceps Curl', muscleGroups: ['Biceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows beside your body and lower fully.' },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Dumbbell', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Hold the weight at your chest and sit between your hips.' },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroups: ['Shoulders', 'Triceps'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your back supported and finish with your hands above your shoulders.' },
  { id: 'face-pull', name: 'Face Pull', muscleGroups: ['Rear delts', 'Upper back'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '12–15 reps', instructions: 'Pull the rope toward eye level and rotate your hands apart.' },
  { id: 'cable-triceps-pushdown', name: 'Cable Triceps Pushdown', muscleGroups: ['Triceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows still and straighten your arms completely.' },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your back on the pad and let your knees track over your toes.' },
  { id: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', muscleGroups: ['Glutes', 'Hamstrings'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Tuck your chin and finish by squeezing your glutes, not arching your back.' },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Lower your back knee and keep pressure through the front foot.' },
  { id: 'lying-leg-curl', name: 'Lying Leg Curl', muscleGroups: ['Hamstrings'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your hips against the pad and curl without swinging.' },
  { id: 'assisted-pull-up', name: 'Assisted Pull-up', muscleGroups: ['Back', 'Biceps'], equipment: 'Machine', mode: 'assisted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Use the minimum assistance that lets you reach the bar with control.' },
  { id: 'chest-supported-dumbbell-row', name: 'Chest-supported Row', muscleGroups: ['Back', 'Biceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your chest on the bench and pull toward your hips.' },
  { id: 'pec-deck-fly', name: 'Cable Chest Fly', muscleGroups: ['Chest'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep a soft elbow and bring your hands together in a wide arc.' },
  { id: 'standing-calf-raise', name: 'Standing Calf Raise', muscleGroups: ['Calves'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 4, target: '10–15 reps', instructions: 'Pause at the top and lower into a comfortable stretch.' },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroups: ['Core'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–12 reps each side', instructions: 'Brace your trunk and resist turning as you press away.' },
  { id: 'barbell-back-squat', name: 'Barbell Back Squat', muscleGroups: ['Quads', 'Glutes', 'Core'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '5–8 reps', instructions: 'Brace before each rep and keep the bar balanced over mid-foot.' },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroups: ['Quads'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Lift smoothly and pause briefly with your knees straight.' },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroups: ['Biceps', 'Forearms'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your palms facing in and avoid swinging the weights.' },
  { id: 'overhead-triceps-extension', name: 'Overhead Triceps Extension', muscleGroups: ['Triceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows pointing forward and reach to full extension.' },
  { id: 'plank', name: 'Plank', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'duration', defaultSets: 3, target: '30–60 seconds', instructions: 'Squeeze your glutes and keep a straight line from head to heels.' },
  { id: 'side-plank', name: 'Side Plank', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'duration', defaultSets: 3, target: '20–45 seconds each side', instructions: 'Stack your shoulders and hips while pushing the floor away.' },
  { id: 'hanging-knee-raise', name: 'Hanging Knee Raise', muscleGroups: ['Core', 'Hip flexors'], equipment: 'Pull-up bar', mode: 'bodyweight_reps', defaultSets: 3, target: '8–15 reps', instructions: 'Curl your pelvis upward and avoid swinging between reps.' },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'bodyweight_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Press your lower back down while extending opposite arm and leg.' },
];

export const exerciseById = new Map(exercises.map((exercise) => [exercise.id, exercise]));

export const exerciseFilters = ['All', 'Chest', 'Back', 'Shoulders', 'Arms', 'Quads', 'Hamstrings', 'Glutes', 'Core'] as const;
