import type { Exercise } from './types';

export const exercises: Exercise[] = [
  { id: 'leg-press', name: 'Leg Press', muscleGroups: ['Quads', 'Glutes'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your lower back supported and drive through your whole foot.' },
  { id: 'bench-press', name: 'Bench Press', muscleGroups: ['Chest', 'Triceps'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Pin your shoulder blades, lower with control, and press over your chest.' },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroups: ['Back', 'Biceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Pull your elbows toward your ribs without leaning far back.' },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroups: ['Shoulders'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '12–15 reps', instructions: 'Lead with your elbows and stop near shoulder height.' },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroups: ['Core'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Curl your ribs toward your pelvis without pulling with your arms.' },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroups: ['Hamstrings', 'Glutes'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Push your hips back and keep the bar close to your legs.' },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', muscleGroups: ['Chest', 'Shoulders'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Set a low incline and press the dumbbells slightly inward.' },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroups: ['Back', 'Biceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your torso tall and bring the handle toward your lower ribs.' },
  { id: 'dumbbell-biceps-curl', name: 'Dumbbell Biceps Curl', muscleGroups: ['Biceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows beside your body and lower fully.' },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Dumbbell', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Hold the weight at your chest and sit between your hips.' },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroups: ['Shoulders', 'Triceps'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your back supported and finish with your hands above your shoulders.' },
  { id: 'face-pull', name: 'Face Pull', muscleGroups: ['Rear delts', 'Upper back'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '12–15 reps', instructions: 'Pull the rope toward eye level and rotate your hands apart.' },
  { id: 'cable-triceps-pushdown', name: 'Cable Triceps Pushdown', muscleGroups: ['Triceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows still and straighten your arms completely.' },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your back on the pad and let your knees track over your toes.' },
  { id: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', muscleGroups: ['Glutes', 'Hamstrings'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Tuck your chin and finish by squeezing your glutes, not arching your back.' },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroups: ['Quads', 'Glutes'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Lower your back knee and keep pressure through the front foot.' },
  { id: 'lying-leg-curl', name: 'Lying Leg Curl', muscleGroups: ['Hamstrings'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your hips against the pad and curl without swinging.' },
  { id: 'assisted-pull-up', name: 'Assisted Pull-up', muscleGroups: ['Back', 'Biceps'], equipment: 'Machine', mode: 'assisted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Use the minimum assistance that lets you reach the bar with control.' },
  { id: 'chest-supported-dumbbell-row', name: 'Chest-supported Row', muscleGroups: ['Back', 'Biceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your chest on the bench and pull toward your hips.' },
  { id: 'pec-deck-fly', name: 'Cable Chest Fly', muscleGroups: ['Chest'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep a soft elbow and bring your hands together in a wide arc.' },
  { id: 'standing-calf-raise', name: 'Standing Calf Raise', muscleGroups: ['Calves'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 4, target: '10–15 reps', instructions: 'Pause at the top and lower into a comfortable stretch.' },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroups: ['Core'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–12 reps each side', instructions: 'Brace your trunk and resist turning as you press away.' },
  { id: 'barbell-back-squat', name: 'Barbell Back Squat', muscleGroups: ['Quads', 'Glutes', 'Core'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '5–8 reps', instructions: 'Brace before each rep and keep the bar balanced over mid-foot.' },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroups: ['Quads'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Lift smoothly and pause briefly with your knees straight.' },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroups: ['Biceps', 'Forearms'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your palms facing in and avoid swinging the weights.' },
  { id: 'overhead-triceps-extension', name: 'Overhead Triceps Extension', muscleGroups: ['Triceps'], equipment: 'Cable', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your elbows pointing forward and reach to full extension.' },
  { id: 'plank', name: 'Plank', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'duration', defaultSets: 3, target: '30–60 seconds', instructions: 'Squeeze your glutes and keep a straight line from head to heels.' },
  { id: 'side-plank', name: 'Side Plank', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'duration', defaultSets: 3, target: '20–45 seconds each side', instructions: 'Stack your shoulders and hips while pushing the floor away.' },
  { id: 'hanging-knee-raise', name: 'Hanging Knee Raise', muscleGroups: ['Core', 'Hip flexors'], equipment: 'Pull-up bar', mode: 'bodyweight_reps', defaultSets: 3, target: '8–15 reps', instructions: 'Curl your pelvis upward and avoid swinging between reps.' },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'bodyweight_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Press your lower back down while extending opposite arm and leg.' },
  { id: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', muscleGroups: ['Chest', 'Triceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your feet planted, lower the dumbbells beside your chest, and press without bouncing.' },
  { id: 'push-up', name: 'Push-up', muscleGroups: ['Chest', 'Triceps', 'Core'], equipment: 'Bodyweight', mode: 'bodyweight_reps', defaultSets: 3, target: '8–20 reps', instructions: 'Keep your body in one line and lower your chest between your hands.' },
  { id: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroups: ['Shoulders', 'Triceps'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Brace your trunk and press the dumbbells overhead without arching your lower back.' },
  { id: 'pull-up', name: 'Pull-up', muscleGroups: ['Back', 'Biceps'], equipment: 'Pull-up bar', mode: 'bodyweight_reps', defaultSets: 3, target: '5–10 reps', instructions: 'Start from a controlled hang and drive your elbows down until your chin clears the bar.' },
  { id: 'barbell-bent-over-row', name: 'Barbell Bent-over Row', muscleGroups: ['Back', 'Biceps', 'Rear delts'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '6–10 reps', instructions: 'Hinge with a braced torso and pull the bar toward your lower ribs.' },
  { id: 'one-arm-dumbbell-row', name: 'One-arm Dumbbell Row', muscleGroups: ['Back', 'Biceps'], equipment: 'Dumbbell', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Support yourself on a bench and pull the dumbbell toward your hip without twisting.' },
  { id: 'barbell-deadlift', name: 'Barbell Deadlift', muscleGroups: ['Hamstrings', 'Glutes', 'Back'], equipment: 'Barbell', mode: 'weighted_reps', defaultSets: 3, target: '4–8 reps', instructions: 'Brace before lifting, keep the bar close, and stand tall without leaning back.' },
  { id: 'walking-lunge', name: 'Walking Lunge', muscleGroups: ['Quads', 'Glutes'], equipment: 'Dumbbells', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps each side', instructions: 'Take a stable step, lower both knees with control, and drive through the front foot.' },
  { id: 'seated-leg-curl', name: 'Seated Leg Curl', muscleGroups: ['Hamstrings'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Keep your hips down and curl through a full comfortable range without swinging.' },
  { id: 'seated-calf-raise', name: 'Seated Calf Raise', muscleGroups: ['Calves'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 4, target: '10–15 reps', instructions: 'Let your heels lower under control, then rise fully and pause at the top.' },
  { id: 'reverse-pec-deck', name: 'Reverse Pec Deck', muscleGroups: ['Rear delts', 'Upper back'], equipment: 'Machine', mode: 'weighted_reps', defaultSets: 3, target: '12–15 reps', instructions: 'Keep your chest against the pad and open your arms without shrugging.' },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroups: ['Biceps'], equipment: 'EZ-bar', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your upper arms on the pad and lower the bar under control.' },
  { id: 'lying-triceps-extension', name: 'Lying Triceps Extension', muscleGroups: ['Triceps'], equipment: 'EZ-bar', mode: 'weighted_reps', defaultSets: 3, target: '8–12 reps', instructions: 'Keep your upper arms steady and bend only at the elbows as the bar moves toward your forehead.' },
  { id: 'ab-wheel-rollout', name: 'Ab Wheel Rollout', muscleGroups: ['Core'], equipment: 'Ab wheel', mode: 'bodyweight_reps', defaultSets: 3, target: '6–12 reps', instructions: 'Brace your trunk and roll only as far as you can without letting your lower back sag.' },
  { id: 'reverse-crunch', name: 'Reverse Crunch', muscleGroups: ['Core'], equipment: 'Bodyweight', mode: 'bodyweight_reps', defaultSets: 3, target: '10–15 reps', instructions: 'Curl your pelvis toward your ribs with control instead of swinging your legs.' },
];

export const exerciseById = new Map(exercises.map((exercise) => [exercise.id, exercise]));

export const exerciseFilters = ['All', 'Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Core'] as const;
export type ExerciseFilter = (typeof exerciseFilters)[number];

export function exerciseMatchesFilter(exercise: Exercise, filter: ExerciseFilter) {
  if (filter === 'All') return true;
  if (filter === 'Arms') return exercise.muscleGroups.some((group) => ['Biceps', 'Triceps', 'Forearms'].includes(group));
  if (filter === 'Legs') return exercise.muscleGroups.some((group) => ['Quads', 'Hamstrings', 'Glutes', 'Calves'].includes(group));
  return exercise.muscleGroups.includes(filter);
}
